### ISSUE TITLE
Slider component

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#102]
[The Slider component that is currently existent on bit.dev](https://bit.dev/dhi-solutions/shared/ui/slider) could be added to the lab and enhanced.

Some fixes could be

- to add an useEffect hook that sets the value to defaultValue as in
```
  useEffect(() => {
    
    setValue(defaultValue)

  }, [defaultValue])
```
- align the title with the right ThemeProvider Typography variant
- Add a story on how to use it - [there's one already here as well](https://storybookdev.z6.web.core.windows.net/?path=/docs/slider--default-story)

**Comment by nishit-prasad** [comment]
Hello, I am new and would like to work on it. Can I take this up if it's available?

**Comment by bertearazvan** [comment]
> Hello, I am new and would like to work on it. Can I take this up if it's available?

Sure, feel free to give it a try. Make sure to look up the [contributing guidelines](https://github.com/DHI/react-components/blob/master/packages/react-components-lab/docs/CONTRIBUTING.md)

Be aware that this component is not necessarily used widely within DHI, but rather more in the GRAS department.

**Comment by nishit-prasad** [comment]
Thank you for getting back! I can check other issues that can be used within DHI but they don't have "good-first-issue" label attached. So, was wondering whether you can direct me to one under DHI?

I am good with either ways.

**Comment by bertearazvan** [comment]
> Thank you for getting back! I can check other issues that can be used within DHI but they don't have "good-first-issue" label attached. So, was wondering whether you can direct me to one under DHI?

Can't really scope out other issues that are relevant and can be worked on at the moment. There are a few, but they are awaiting some coordination with the UI/UX department. Ideally, you could spot components that you use in the department you are part of, and if you consider it could be reused by others feel free to raise an Issue and open PR for it. Any sort of contribution is welcomed.

Recently we added two hooks to the `react-components-lab` package. It would be nice if we can showcase them in the storybook somehow - with some code example. 

I think @brigittarucz had some idea about it. Brigitta, could you create an issue to summarize what you had in mind?

**Comment by brigittarucz** [comment]
I have created #155 if you want to have a look @nishit-prasad !

**Comment by nishit-prasad** [comment]
Thank you guys! Appreciate the guidance and direction. I'll take a look.
