### ISSUE TITLE
Update people list in "Board of maintainers" section in Readme

### ISSUE THREAD

**Issue by rosudhi** [DHI/react-components#104]
People list are not up to date and perhaps need a bit styling on it? such as add an avatar with photo? :)

**Comment by bertearazvan** [comment]
You probably noticed that someone is missing, could you update the list with who you think is missing?

Not sure what to say about the avatar photo. That may change over time and it would require us to keep it updated. But maybe some avatar icons would play nicely. What do you think?

**Comment by rosudhi** [comment]
We're missing me and Jonas :)

The idea is to have similar like in contributors section, but with some details and slighly bigger and sure we have to keep the list up to date, that's what maintainers do, right? :)
Here, i propose the details:
- Photo/icon avatar this could be any with circular/rectangular shape. I think icon also nice.
- Clickable and linked to provided url, could be personal website or just github profile.
- Small icons that represent his/her role in this repo and placed on beneath avatar. The role could be `Coder`, `Reviewer`, `Tester`, etc.
-  else ?

**Comment by bertearazvan** [comment]
I would suggest using the avatars from GitHub as images by using the GitHub API. I would suggest the GitHub profile as a link, cus you can add on your profile your personal website.

The roles you proposed sound good to me, a person could have multiple roles. We can add them as custom badges maybe 😎
