### ISSUE TITLE
Unconsistent code formatting

### ISSUE THREAD

**Issue by rosudhi** [DHI/react-components#106]
Currently there is auto code formatting on saving which is based on eslint rule but this behaviour is not work as expected when using prettier. See folowing pictures:
![image](https://user-images.githubusercontent.com/46663012/115675552-e3e87f00-a378-11eb-93c0-9ccddb6b719b.png)

prettier result:
![image](https://user-images.githubusercontent.com/46663012/115675994-59544f80-a379-11eb-8d14-41ed857463ac.png)

auto save result:
![image](https://user-images.githubusercontent.com/46663012/115676114-75f08780-a379-11eb-80bc-5fd02abdc924.png)

**Comment by rihr** [comment]
I don't think it was actually intended to work with prettier as the formatter. There are prettier rules being used under the hood but all the actual formatting is done by ESLint.
As far as I know prettier can't handle all formatting like ESLint can in this case.
Should be easy to disable prettier as the formatter per VSCode workspace

**Comment by rosudhi** [comment]
Thanks for the response.
I agree that ESLint can do more job than Prettier, they can do both code-quality and code-formatting rule. I used to split the job of their, so we can use ESLint for code-quality concerns and Prettier for code-formatting concerns. Even though, splitting this is unnecessary, but we can have cleaner rules settings and also formatter work consistently.
Cmiiw.
