### ISSUE TITLE
Theme Provider doesn't seem to work when imported

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#114]
I am not sure why but the ThemeProvider doesn't seem to apply the theme 
![b26fe9a3efecc7cf34bf5a649a49843e](https://user-images.githubusercontent.com/30385700/116384267-fac71f80-a817-11eb-91a8-fe99a6159b65.png)

![afsgdfgadas](https://user-images.githubusercontent.com/30385700/116384608-509bc780-a818-11eb-95c0-87fc69515421.png)

**Comment by elbys** [comment]
Hey there is no property grey in the pallete... 

![image](https://user-images.githubusercontent.com/54185768/116512659-ab8cf780-a8c8-11eb-9139-6bd01fd7c130.png)

**Comment by bertearazvan** [comment]
Somehow it worked by removing the node_modules but then I encountered other problems with overrides and left it away. Not sure what was the problem, but I tried adding this theme to an already made project and that was an overhead.
