### ISSUE TITLE
Mike icons migration 

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#123]
Related to migrating the mike icons into the react-components lab and the considerations in this regard such as using the icons from a separate package and so on.

CC @rihr

**Comment by rihr** [comment]
I think using svgr would make sense here. Would be good if src files only contain .svg files, and 1 template. Svgr could then be used to generate all the react components to a gitignored dist dir, and you'd publish that as the icons package.
A possible way to do it is to use a custom node script that generates the components with a template, and the copies a package.json template to the dist dir. The script could then be put under package.json as "build".

https://react-svgr.com/docs/cli/
