### ISSUE TITLE
Customize the font with mikeSharedTheme

### ISSUE THREAD

**Issue by hawklorry** [DHI/react-components#129]
Is there a way to use another font with mikeSharedTheme? An example would be great.

**Comment by rosudhi** [comment]
See the following example:
![image](https://user-images.githubusercontent.com/46663012/121177922-26faa500-c888-11eb-87f0-02d4dbd0c2d6.png)

currently, if you implement above codes, you may see the result as expected, but typescript compiler will noticed some error/warning. these will go away until the PR is merged.
