### ISSUE TITLE
useBelow hook

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#136]
@rihr Would you be so kind to create a PR with the hook you created? I really think it's useful and I find myself looking for it quite often. It would be nice if we could just import it from the lib.

**Comment by goneale** [comment]
Hi guys
Very intriguing hook here. What does it do, or where can we see samples for it? Thanks

**Comment by rihr** [comment]
We usually use it for changing prop values or conditionally rendering something when the window width is below the width of a certain breakpoint defined in the Material UI theme

Can be used like this 

```js
const belowMd = useBelow('md')

return (
		<Box
			display={'flex'}
			flexDirection={belowMd ? 'column' : 'row'}
...
...
