### ISSUE TITLE
Create stories for hooks

### ISSUE THREAD

**Issue by brigittarucz** [DHI/react-components#155]
When it comes to the existent hooks we do not have a way to _showcase them visually_. 

As a solution, ideally under a new Story item dropdown "Hooks", we could find the existent ones from the hooks folder. Each would have a snippet representing their source code and it would be good to have an example of their implementation. 

A good place to start would be to look how the `<Syntax/>` [component](https://github.com/DHI/react-components/blob/master/packages/react-components-lab/src/components/Syntax/Syntax.tsx) is implemented.

**Comment by nishit-prasad** [comment]
Hey @brigittarucz I guess I can take a shot at this. Gives me room to learn and explore.

Do you have any directions on how to get started with development setup? I can check docs but want to make sure I am in the right direction.

**Comment by brigittarucz** [comment]
Hello, @nishit-prasad. It would be easier to tackle this ( if you still need direction ) by pinpointing any difficulties or confusions that you experience.
