### ISSUE TITLE
Should we have app-based icons in the @icons lib?

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#209]
There are some icons like `DataLink` or `DataAdmin` that shouldn't change color once compiled since they contain some specific colors that shouldn't be replaced.

**Comment by bertearazvan** [comment]
@rihr?

**Comment by rihr** [comment]
I copied all icons over, except ones that were more like images than icons
Ones like DataLink or DataAdmin definitely don't look useful to share to me

Should we actually look through all the existing icons and find ones to delete or just leave them for now and just QA new icons?

**Comment by bertearazvan** [comment]
I am up for looking through all the existing icons, and deleting the ones like "DataLink" or "DataAdmin" which are app-specific.

I would also suggest removing the ones that are found in `@material-ui/icons` like the `Add`, or `User` which is `PersonOutlineIcon` in MuI.

Worth mentioning is that they have a new package for icons, which is `@mui/icons-material`

**Comment by rihr** [comment]
Sounds good. Make sure the similar icons in MUI actually are the same. Maybe there's small edits to them for UI/UX reasons
