### ISSUE TITLE
Speed up lab workflow in PRs

### ISSUE THREAD

**Issue by rihr** [DHI/react-components#225]
Should aim to half the the PR deployment pipeline time

Things to try:
- Set up github actions workflow to cache all package `node_modules` dirs
- Check if installing dependencies for lab package separately is required

**Comment by bertearazvan** [comment]
> Things to try:

- [ ] Set up github actions workflow to cache all package `node_modules` dirs

- don't think that caching node_modules would be the solution to go for, considering that we don't have multiple steps but only 1. Maybe improving the build time, and only installing the dependencies needed for the given package, somehow,

- [x] Check if installing dependencies for lab package separately is required

**Comment by bertearazvan** [comment]
@rihr As far as I can see, I am not sure if I can further speed up the pipeline. As you mentioned, we could cache the `node_modules` but that part is useful if there are workflows that depend on one another, which is not the case for us.

Some options would be:
- to save the node_modules as artifacts but I don't think it's worth the overhead or
- use yarn 2 workspaces and have the cached node_modules committed to git, but that would need further coordination with the others.

**Comment by rihr** [comment]
Just an idea - did you look into lerna dependency hoisting? If hoisting isn't enabled, then dependencies aren't shared between the packages, even if they are identical. I think hoisting is enabled by default in yarn workspaces

**Comment by bertearazvan** [comment]
Nice idea @rihr,

It seems that lerna wants us to use `yarn workspaces` if we want to use the `--hoist` flag. Do you think yarn 1 workspaces is worth a shot, or should we propose directly using "yarn 2"?

**Comment by rihr** [comment]
I expected yarn 1 workspaces to be already enabled in our current setup. Worth trying it, as that's a pretty small change

**Comment by bertearazvan** [comment]
I realized that shortly, indeed, yarn 1 workspaces was enabled initially. I will give yarn 2 a shot to see if it's more performant in the pipeline.

**Comment by bertearazvan** [comment]
I think this issue can be considered complete. We should create another one based on new specs if needed. #251
