### ISSUE TITLE
Error in @dhi/react-components - Can't resolve './react-components.cjs.development.js'

### ISSUE THREAD

**Issue by GGAlanSmithee** [DHI/react-components#267]
When attempting to use later versions of @dhi/react-components-lab` I get the error `Module not found: Error: Can't resolve '@dhi/react-components-lab'`. I can install the package, but it's not found when attempting to use it.

I tried downgrading to a previous version (`"@dhi/react-components-lab": "1.10.0",`) which works as expected. Not sure exactly which version between the two that broke it.

**Comment by GGAlanSmithee** [comment]
PS. I'm installing it using the `--legacy-peer-deps` flag, if that has anything to do with it.

**Comment by bertearazvan** [comment]
Hi @GGAlanSmithee and thank you for using our package. We spotted this issue a few days ago but we are still investigating what went wrong. I will look into deprecating the versions that are not working. 

Until then, I believe that `1.12.0` is the latest version that works as it should.

**Comment by bertearazvan** [comment]
The versions that were not working should be now deleted. The latest version is `1.12.4` and it should work as expected.

**Comment by GGAlanSmithee** [comment]
Thanks @bertearazvan

**Comment by bertearazvan** [comment]
This is related to `@dhi/react-components` and not `@dhi/react-components-lab`, right?

**Comment by bertearazvan** [comment]
Please use `0.6.76` in the meantime. https://github.com/DHI/react-components/packages/422920?version=0.6.76.

@FranzThomsen1089. the version `0.6.77` doesn't include the build files in the `dist` folder. Probably worth deprecating version  `0.6.77` and republishing the changes under `0.6.78` if needed.

**Comment by GGAlanSmithee** [comment]
@bertearazvan yes, that is correct, I will downgrade - thanks!

**Comment by GGAlanSmithee** [comment]
This worked BTW, so have locked the version for now.

**Comment by bertearazvan** [comment]
@GGAlanSmithee new versions have been released since yesterday, feel free to try them out.

**Comment by GGAlanSmithee** [comment]
@bertearazvan thanks! Will do.
