### ISSUE TITLE
ErrorScreen

### ISSUE THREAD

**Issue by rihr** [DHI/react-components#66]
![image](https://user-images.githubusercontent.com/67369454/105085437-088e3b80-5a98-11eb-9703-6e31493cd200.png)
Does not have to look like anything in the screenshot - could be a different design entirely, including the DHI logo and be in general more subtle and generic.

Considerations
- Should support severity of errors, full app crash, 404 and other HTTP errors
- Should be usable as a full-screen component and as a view component, replacing the content below the navigation bar, for instance
- Should possibly support error handling, with a wrapper or alternate ErrorBoundary component, possibly integrated with Sentry - if possible should be error handler agnostic
- Custom label props for localization with defaults in English

**Comment by DenizYil** [comment]
Added - it's called `SplashScreen` and can be viewed here:
https://react-components-lab.dhigroup.com/?path=/story/components-splashscreen--mobile-splash
