### ISSUE TITLE
Theme provider

### ISSUE THREAD

**Issue by elbys** [DHI/react-components#68]
Add typing for color palette

**Comment by elbys** [comment]
Seems like we have high priority on this one... Should I help with this?

**Comment by rihr** [comment]
I remember the ThemeProvider on bit.dev also had the `overrides` prop type set to required, which it shouldn't be

**Comment by rosudhi** [comment]
if we going to use PaletteOptions types, then we have to remove darkGrey, mediumGrey, lightGrey and ultimate property in current palette. PaletteOptions types has grey property which has Partial<Color> types. i think we have to define all of these colors. Example:
```
grey: {
    50: '',
    100: '',
    200: '',
    300: '',
    400: '',
    500: '',
    600: '',
    700: '',
    800: '',
    900: '',
}
```
thought?
- other properties already use Mui types as well.

**Comment by elbys** [comment]
Hey,

I am not sure we have to remove them....  @MadsZeneli  do you have comments on this ?

**Comment by bertearazvan** [comment]
This should be closed I assume. When creating a PR, we can use the Close/Fix keywords followed by the issue number ex. `Close #1`
