### ISSUE TITLE
Staging deployments for PRs?

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#97]
When reviewing a PR when a component gets added to the lab, it would be useful to see a staging deployment with how the component looks in the storybook. At the same time, it would help in the case of storybook UI enhancements. 

At the moment, the static-web-app(preview) resource is taking care of that out of the box. Are there other Azure resources having this feature that might not be in the "preview" stage?

This feature will require some pipeline work to only deploy stuff related to the react-components-lab.

@elbys @rihr @j08lue @rosudhi

**Comment by j08lue** [comment]
> Are there other Azure resources having this feature that might not be in the "preview" stage?

Just use preview for now. If they stop it or it breaks, we can find something else. But it is so nice and easy, so there is little risk with using that, IMO.

**Comment by bertearazvan** [comment]
> Just use preview for now. If they stop it or it breaks, we can find something else. But it is so nice and easy, so there is little risk with using that, IMO.

In this case, maybe it would be useful to ask for more static web apps resources on our organization, as we have reached the limit (10). Do you think that would be possible?

**Comment by j08lue** [comment]
Yes, Azure support has before responded quite quickly - not sure how they are about these cheap services, though. Let's try.

**Comment by bertearazvan** [comment]
This could be prioritized now as the service is out of preview :)
